### ISSUE TITLE
wt5 event model -- add seq_num

### ISSUE THREAD

**Issue by kameyer226** [wright-group/bluesky-in-a-box#59]
Hello,

I am thinking of adding the sequence number as an additional data channel , which would probably just be a line or two after 181 in the wt5_event_model.py.

While the labtime can theoretically be used to back out the index/sequence number of the corresponding datum, it would be nice to have this as an integer and not do the calculations post acquisition.

It would help ensure we know the data collection order of a scan without resorting to values stored in a queue, in our attempt to ensure that all important values are appropriately incorporated into the wt5 file.  (Data collection order can help determine when extraneous events may occur such as A/Cs firing, loss of sample integrity, etc.)

**Comment by ksunden** [comment]
I see no reason to do this... we already use `seq_num` to determine which portion of the arrays to write for a given datum:

https://github.com/wright-group/bluesky-in-a-box/blob/9f0260be739ecd83d8486020d4b1a806858a0783/wt5/wt5_event_model.py#L186

If we were to receive events out of order, it would just work.
If we were to miss an event, it would just have `nan` in all channels.

The timestamp is provided by bluesky, not added at data recording time, so I do not see a reasonable case for the timestamps to be insufficient.

I guess, snaking ordering may be a reason that the linked portion of the code may need to grow more complicated, actually... and also the only real reason for `seq_num` to not just simply be equivalent to `np.arange(size).reshape(shape)`. but again, if the goal is to associate with other external events, timestamps are what you want, and seq_num is kind of useless post fact.

I will not hard stop it from happening, but I also do not understand its utility.

**Comment by ddkohler** [comment]
The concern about keeping data points in order is a non-issue, but if the main concern is to have your data points indexed by integer values without directly invoking numpy tools, I would favor storing a function in the post-processing workflow, rather than storing a redundant variable in all raw data.  I know you mentioned you do not want to do this, but the index generation is perhaps simpler than you realized?  If you think a function needs to be generally available, WrightTools.kit might be a good location for such a function.

**Comment by kameyer226** [comment]
Yes, I think labtime would probably be better, starting from zero, for what I was thinking of.   Ok, thanks!
